---
deployment:
  task:
    - export DEPLOYPATH=/home3/sabimael/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp main.css $DEPLOYPATH
    - /bin/cp main.js $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R components $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
    - /bin/cp -R scripts $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH
  


